//export * from './nombre.interface;
export * from './admin.interface';
export * from './auth.interface';
export * from './category.interface';
export * from './client.interface';
export * from './default.interface';
export * from './orders.interface';
export * from './payment.interface';
export * from './products.interface';
export * from './retail.interface'
export * from './role.interface';
export * from './upload.interface';
export * from './user.interface';
export * from './userAccess.interface';
export * from './subscriber.interface';
export * from './size.interface';